spring.application.name=UserService
server.port=8081
spring.datasource.generate-unique-name=false
management.endpoints.web.exposure.include=health,info,metrics

# PostgreSQL database config
spring.datasource.url=jdbc:postgresql://192.168.0.225:5432/thelastfork_db
spring.datasource.username=admin
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false

# RabbitMQ config
spring.rabbitmq.host=192.168.0.225
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=${RABBITMQ_PASSWORD}